language: c
os:
  - linux
  - osx
compiler:
  - clang
  - gcc
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update -qq ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -qq check libc-ares-dev ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install check c-ares gnutls ; fi
install: autoreconf --install
script: ./configure && make && make check
